using FlareQuotes.Core.Models;

namespace FlareQuotes.Core.Media;

public static class MediaCatalog
{
    public static readonly MediaOption[] Classic = [
        new("fg_silver", "1/2\" Reflective Silver Fire Glass", "Reflective Silver Fire Glass", "fireglass", false,
            ["reflective silver", "media-fg-silver", "cmdfgs"]),
        new("fg_bronze", "1/2\" Reflective Bronze Fire Glass", "Reflective Bronze Fire Glass", "fireglass", false,
            ["reflective bronze", "media-fg-bronze", "cmdfgbr"]),
        new("fg_black", "1/2\" Black Fire Glass", "Black Fire Glass", "fireglass", false,
            ["black fire glass", "black crushed glass", "media-fg-black", "cmdfgbl"]),
        new("fg_ice", "1/2\" Reflective Ice Fire Glass", "Reflective Ice Fire Glass", "fireglass", false,
            ["reflective ice", "media-fg-ice", "cmdfgic"]),
        new("fg_clear", "1/2\" Clear Crushed Glass", "Clear Crushed Glass", "fireglass", false,
            ["clear crushed glass", "media-fg-clear", "cmdfgcl"]),
        new("pd_black", "Zircon Black Diamonds", "Zircon Black Diamonds", "raindrop_diamonds", false,
            ["zircon black diamonds", "media-pd-black", "cmdpdb"]),
        new("pd_rain", "Rain Drop Diamonds", "Rain Drop Diamonds", "raindrop_diamonds", false,
            ["rain drop diamonds", "raindrop diamonds", "media-pd-rain", "cmdpdr"]),
        new("cp_white", "White Ceramic Pebbles", "White Ceramic Pebbles", "ceramic_pebbles", false,
            ["white ceramic pebbles", "media-cp-white", "cmdcpw"]),
        new("cp_black", "Black Ceramic Pebbles", "Black Ceramic Pebbles", "ceramic_pebbles", false,
            ["black ceramic pebbles", "media-cp-black", "cmdcpb"]),
        new("cp_earth", "Earth Mix Ceramic Pebbles", "Earth Mix Pebbles", "ceramic_pebbles", false,
            ["earth mix pebbles", "media-cp-earth", "cmdcpe"]),
        new("gl_white", "Ceramic White Logs", "Ceramic White Logs", "white_logs", false,
            ["ceramic white logs", "white logs", "media-gl-white", "cmdglw"]),
        new("gl_wood", "Ceramic Logs", "Ceramic Logs", "ceramic_logs", false,
            ["ceramic logs", "media-gl-wood", "cmdglwo"]),
        new("gl_branches", "Ceramic Branches", "Ceramic Branches", "branches", false,
            ["ceramic branches", "branches", "media-gl-branches", "cmdglb"]),
        new("gl_embers_tan", "Tan Embers", "Tan Embers", "embers", false, ["tan embers", "media-gl-embers", "cmdgle"]),
        new("gl_embers_black", "Black Embers", "Black Embers", "embers", false,
            ["black embers", "media-gl-embers-bla", "cmdgleb"]),
    ];

    public static readonly MediaOption[] Premium = [
        new("gold_glass", "Gold Crushed Glass", "Gold Glass", "fireglass", true, ["gold crushed glass", "pfg-gold"]),
        new("aqua_glass", "Aqua Crushed Glass", "Aqua Glass", "fireglass", true, ["aqua crushed glass", "pfg-aqua"]),
        new("black_stones", "Premium Black Stones", "Black Stones", "premium_stones", true,
            ["premium black stones", "black stones", "ps-bla"]),
        new("white_stones", "Cottage White Stones", "White Stones", "premium_stones", true,
            ["cottage white stones", "white stones", "ps-white"]),
        new("grey_balls_2", "Cape Grey 2\" Stone Balls", "Grey 2\" Balls", "stone_uniform_2", true,
            ["cape grey 2", "grey stone balls 2", "psb-grey-u2"]),
        new("grey_balls_4", "Cape Grey 4\" Stone Balls", "Grey 4\" Balls", "stone_uniform_4", true,
            ["cape grey 4", "grey stone balls 4", "psb-grey-u4"]),
        new("grey_balls_mixed", "Cape Grey Mixed Stone Balls", "Grey Mixed Balls", "stone_mixed", true,
            ["cape grey mixed", "grey mixed stone balls", "psb-grey-m"]),
        new("white_balls_2", "Cottage White 2\" Stone Balls", "White 2\" Balls", "stone_uniform_2", true,
            ["cottage white 2", "white stone balls 2", "psb-w-u2"]),
        new("white_balls_4", "Cottage White 4\" Stone Balls", "White 4\" Balls", "stone_uniform_4", true,
            ["cottage white 4", "white stone balls 4", "psb-w-u4"]),
        new("white_balls_mixed", "Cottage White Mixed Stone Balls", "White Mixed Balls", "stone_mixed", true,
            ["cottage white mixed", "white mixed stone balls", "psb-w-m"]),
        new("black_balls_2", "Matte Black 2\" Stone Balls", "Black 2\" Balls", "stone_uniform_2", true,
            ["matte black 2", "black stone balls 2", "psb-bla-u2"]),
        new("black_balls_4", "Matte Black 4\" Stone Balls", "Black 4\" Balls", "stone_uniform_4", true,
            ["matte black 4", "black stone balls 4", "psb-bla-u4"]),
        new("black_balls_mixed", "Matte Black Mixed Stone Balls", "Black Mixed Balls", "stone_mixed", true,
            ["matte black mixed", "black mixed stone balls", "psb-bla-m"]),
        new("driftwood", "Driftwood", "Driftwood", "driftwood", true,
            ["driftwood", "premium driftwood", "small driftwood", "large driftwood", "pgl-drift-s", "pgl-drift-l"]),
        new("birchwood", "Birchwood", "Birchwood", "birchwood", true,
            ["birchwood", "psa-birch", "pmdbirch", "pmd birch"]),
        new("tr42bch", "Small Birch Logs for Traditional 42\"", "Small Birch Logs for Traditional 42\"",
            "traditional_birch_42", true,
            ["tr42bch", "tr42-birch", "small birch logs", "traditional 42 birch", "birch logs traditional 42"]),
        new("tr46bch", "Small Birch Logs for Traditional 46\"", "Small Birch Logs for Traditional 46\"",
            "traditional_birch_46", true,
            ["tr46bch", "tr46-birch", "small birch logs", "traditional 46 birch", "birch logs traditional 46"]),
        new("loak42", "Large Oak Log Set for Traditional 42\"", "Large Oak Log Set for Traditional 42\"",
            "traditional_oak_42", true, ["loak42", "large oak log set traditional 42", "large oak 42", "oak logs 42"]),
        new("loak46", "Large Oak Log Set for Traditional 46\"", "Large Oak Log Set for Traditional 46\"",
            "traditional_oak_46", true, ["loak46", "large oak log set traditional 46", "large oak 46", "oak logs 46"]),
    ];
}
